Fix sign up validation
BinaryStudioAcademy/bsa-2021-codetrainer pull request #127
Opened 2021-08-17 06:55 UTC by romanortynskyi

2021-08-17 06:56 UTC, romanortynskyi commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Sign-up]  Username validation](https://trello.com/c/I6QxOJ66/120-sign-up-username-validation)

2021-08-17 12:40 UTC, Paul-Vasylenko requested changes

2021-08-17 12:40 UTC, Paul-Vasylenko commented on client/src/components/pages/sign-up/index.tsx
> +		.matches(/^[A-Za-z0-9]+\-?[A-Za-z0-9]+$/, 'Use only letters, numbers and hyphens')
change this to 
[a-zA-Z0-9]+\-?[a-zA-Z0-9]+

According to https://regex101.com/, your validation string-size is always 3 symbols length. We need more

2021-08-19 13:27 UTC, Paul-Vasylenko approved these changes

2021-08-19 13:27 UTC, merged