Feature/home page
BinaryStudioAcademy/bsa-2021-codetrainer pull request #13
Opened 2021-07-29 23:06 UTC by ivaschenkoo

2021-07-29 23:06 UTC, ivaschenkoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Home Page Layout](https://trello.com/c/tU30Dq4L/10-home-page-layout)

2021-07-29 23:06 UTC, ivaschenkoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Home Page Layout](https://trello.com/c/tU30Dq4L/10-home-page-layout)

2021-07-31 15:30 UTC, ivaschenkoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Home Page Layout](https://trello.com/c/tU30Dq4L/10-home-page-layout)

2021-07-31 17:02 UTC, kyrylo-burmelov requested changes
- All mocked data should be in containers. Components are using only for displaying. I would suggest to split page to several containers: Next Task, Community, Feed.

containers:
-- home
---- next-task
---- community
---- feed

components:
-- home. *use this component to render main label (Hi, Rayna) and content of another containers (from props)*
Like this:
```javascript
// components/pages/home
const Home = ({ activeUserName, nextTaskContent, ... }) => {
    return ...
}

// containers/home
const Home = () => {
    // mock data here
    
    return <HomeComponent activeUserName={...} nextTaskContent={ <NextTask /> /* NextTask is container */ } />
}
```
Then mock needed data for each of these container and return needed components. In the future we will add redux state and actions in containers.

It's needed to separate components (only displaying) from containers (logic, without styles). Also you can read [article](https://medium.com/@learnreact/container-components-c0e67432e005)

- See components/index.ts. There should be import for all basic components, all pages etc.. Then you should use created import everywhere.

2021-08-01 12:13 UTC, ivaschenkoo commented on client/src/components/pages/home/components/feed/index.tsx
> +					</Text>
@romanortynskyi fix it please

2021-08-01 12:14 UTC, ivaschenkoo commented on client/src/components/pages/home/components/feed/index.tsx
> +			<Button text="Load more" classList={styles.loadMoreButton} />
@romanortynskyi fix it please

2021-08-01 12:14 UTC, ivaschenkoo commented on client/src/components/pages/home/components/community/index.tsx
> +				</div>
@romanortynskyi fix it please

2021-08-04 09:56 UTC, kyrylo-burmelov approved these changes

2021-08-04 14:26 UTC, merged