Feature/dark theme
BinaryStudioAcademy/bsa-2021-codetrainer pull request #134
Opened 2021-08-18 10:35 UTC by nikita-dnestrov

I dont understand how to set up rerender without reloading the page. For now theme is based on page html tag attribute called data-theme and I am thinking that is a problem. If I'll give data-theme atrribute to, for example, div with id root, the styles mess up and dont work properly. Redux side of this feature seems to work fine and state successfully changes in store. Look for a tip on how to approach this

2021-08-19 18:37 UTC, Paul-Vasylenko requested changes

2021-08-19 18:37 UTC, Paul-Vasylenko commented on client/src/components/pages/home/home-page.module.scss
>  	font-family: 'Montserrat', Arial, sans-serif;
would be good if you change it to variable

2021-08-19 18:37 UTC, Paul-Vasylenko commented on client/src/containers/example/index.tsx
> +}
I don't think this is important, but why do you use connect if you can use useSelector? Also, I thought we use connect function only in class components (not in React.FC), but maybe I am wrong.

2021-08-19 18:37 UTC, Paul-Vasylenko commented on client/src/containers/private-route/index.tsx
> +	const isAuthorized = true;
delete this please.

2021-08-19 18:37 UTC, Paul-Vasylenko commented on client/src/containers/profile/mocks.ts
>  	score: 222,
then score should be 0 I suppose :)

2021-08-19 18:38 UTC, Paul-Vasylenko commented
However you've done nice work :) Small fixes and it's done

2021-08-19 18:49 UTC, nikita-dnestrov commented on client/src/containers/private-route/index.tsx
> +	const isAuthorized = true;
Ah yes, I always forget it

2021-08-20 06:19 UTC, Paul-Vasylenko approved these changes

2021-08-20 06:41 UTC, merged