Added search on clans page
BinaryStudioAcademy/bsa-2021-codetrainer pull request #167
Opened 2021-08-21 19:32 UTC by Paul-Vasylenko

/clans?search=:clanName 

https://trello.com/c/7UfJ0tvV/159-clans-add-searchclanname-param-for-emails

2021-08-21 19:33 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Clans] Add ?search=:clanName param for emails](https://trello.com/c/7UfJ0tvV/159-clans-add-searchclanname-param-for-emails)

2021-08-22 05:10 UTC, svitlua commented on client/src/containers/clans/clan/logic/saga.ts
> +		historyHelper.push('/clans');
use ROUTES const here

2021-08-22 05:10 UTC, svitlua commented on client/src/containers/clans/clans/index.tsx
> +			historyHelper.push('/clan');
use ROUTES const

2021-08-22 05:10 UTC, svitlua commented on client/src/containers/clans/clans/index.tsx
> +		historyHelper.push('/clans');
the same

2021-08-22 05:21 UTC, svitlua requested changes
I don't really understand why we need to have this functionality **/clans?search=:clanName** 
There is already possibility to search by name on Clans page
![image](https://user-images.githubusercontent.com/31032340/130343380-86580760-aa7c-4e78-90a7-6400ed938cbb.png)


I think what we really need is to refactor Clan page to have something like **clan/:clanname** route

Please, explain

2021-08-22 06:06 UTC, Paul-Vasylenko commented
useless

2021-08-22 06:06 UTC, closed without merging