Patch/modal
BinaryStudioAcademy/bsa-2021-codetrainer pull request #19
Opened 2021-07-30 11:41 UTC by dammmula

Create functionality for using modals

2021-07-30 11:44 UTC, dammmula commented
![](https://github.trello.services/images/mini-trello-icon.png) [General Modal Component](https://trello.com/c/PzbBKnez/18-general-modal-component)

2021-07-31 17:35 UTC, kyrylo-burmelov requested changes
- You need to add import of modal component from 'components` folder. See examples from this folder
- We need to have a possibility to use other props from `react-modal` component. So, you need to add one one prop to `Modal` component. For example: `modalProps?: /*here TS interface from lib/*`.  And then spread it to modal component.
- We probably need a possibility to close the popup not only from modal component by clicking icon. Sometimes it's needed to close the  modal from the component from where modal was opened. Looks like it's not possible with your current implementation.
- Let's add possibility to open modal without close icon. When some action from modal is required for continue using application
- See comments below

2021-07-31 17:35 UTC, kyrylo-burmelov commented on client/src/components/modals/modal/index.tsx
> +		footer: React.ReactNode | null;
you can add optional prop

```javascript
footer?: React.ReactNode;
```

2021-07-31 17:35 UTC, kyrylo-burmelov commented on client/src/components/modals/modal/index.tsx
> +				{footer ? <div className={styles.footer}>{footer}</div> : null}
```
{footer && <div className={styles.footer}>{footer}</div>}
```

2021-07-31 17:35 UTC, kyrylo-burmelov commented on client/src/components/modals/modal/index.tsx
> +};
move to config modal/config.ts

2021-08-02 10:26 UTC, kyrylo-burmelov approved these changes
It would be better to add close icon for the header by default. And then add a possibility to hide it with additional props. But let's leave it like this for now

2021-08-02 10:26 UTC, merged