Added main sidebar
BinaryStudioAcademy/bsa-2021-codetrainer pull request #2
Opened 2021-07-28 17:17 UTC by Ev1ch

2021-07-28 17:19 UTC, Ev1ch commented
![](https://github.trello.services/images/mini-trello-icon.png) [Left Sidebar Layout](https://trello.com/c/rm707v3q/7-left-sidebar-layout)

2021-08-01 15:10 UTC, taras-dubyk commented on client/package.json
> -		"prettier": "^2.3.2",
?

2021-08-01 21:31 UTC, taras-dubyk requested changes
Please revert removed prettier dep.

2021-08-02 16:47 UTC, taras-dubyk approved these changes

2021-08-02 16:48 UTC, merged