add Code & Markdown Editor Component
BinaryStudioAcademy/bsa-2021-codetrainer pull request #22
Opened 2021-07-30 19:33 UTC by sFLASHs

2021-07-31 20:34 UTC, kyrylo-burmelov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Code & Markdown Editor Component](https://trello.com/c/ObpyddFn/14-code-markdown-editor-component)

2021-08-01 16:18 UTC, taras-dubyk commented on client/src/components/pages/create-task/common/create-tabs/create-code/index.tsx
> +import { Ace } from 'ace-builds';
combine imports from ace-builds

2021-08-01 21:09 UTC, taras-dubyk commented on client/src/components/pages/create-task/common/create-tabs/create-code/index.tsx
> +);
Seems redundant. Try to import ace-builds before AceEditor.

2021-08-01 21:18 UTC, taras-dubyk commented on client/src/components/pages/create-task/common/create-tabs/create-tabs.tsx
> +		<div className={`${styles.root} ${fullScreen ? styles['edit__fullscreen'] : styles['edit']}`}>
Use [clsx](https://www.npmjs.com/package/clsx)

2021-08-01 21:20 UTC, taras-dubyk commented on client/src/components/pages/create-task/common/create-tabs/header/index.tsx
> +interface IProps {
Rename to IHeaderProps

2021-08-01 21:25 UTC, taras-dubyk commented on client/src/components/pages/create-task/common/create-tabs/create-text/index.tsx
> +	const [value, setValue] = useState<string>(text);
We don't need local state for tab value here. Value should be recieved from parent container.

2021-08-01 21:27 UTC, taras-dubyk requested changes
Issues should be resolved.

2021-08-04 11:15 UTC, taras-dubyk approved these changes

2021-08-04 11:15 UTC, merged