Patch/profile 2
BinaryStudioAcademy/bsa-2021-codetrainer pull request #23
Opened 2021-07-30 21:23 UTC by Paul-Vasylenko

2021-07-30 21:25 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [User Profile page Layout](https://trello.com/c/abnuoOrO/9-user-profile-page-layout)

2021-07-31 15:43 UTC, kyrylo-burmelov requested changes
- Fix folders structure.
See components/index -> you should import page and another reusable components from this place. See existing example for basic components
- Tabs should work as needed (highlight active tab after clicking) but without content. With content only stats tab.
- Index tab?
![image](https://user-images.githubusercontent.com/55874288/127744035-ee37f144-91a0-4a66-b407-482b2b5c10f7.png)
- Carefully review your work. There are a few design mistakes. For example, see this block
![image](https://user-images.githubusercontent.com/55874288/127744070-3332ab28-5f50-4703-949d-92ea2b908a0f.png)
- Community block is not supporting all needed type of view. For example - 0 (0 replies)
- Mocked data should be in container. And there should be separate container for profile page and for each of the route for tabs. 

you need to create new container --> containers/porfile...
```javascript
const Profile = () => {
   return (
      <ProfilePage // this profile page is component
           userInfo={userInfoData}
           activeTab={activeTab}
           tabContent={
               // Here you need to return Container, not component.
               // In this container you should have Routing for different tabs
           }
      />
   )
}
```
- Should add smaller components to basic or common folder. When adding components for whole tab. You can add it to pages - profile - tabs - stats / challenge / solution etc..
- Having in mind that not all users have such details as clan, github url, etc. You need to manage it somehow.

2021-07-31 15:43 UTC, kyrylo-burmelov commented on client/src/containers/routing/index.tsx
> +		<PublicRoute restricted={false} path="/users/:name" component={Profile} />
It should be PrivateRoute. Auth required for seeing this page

2021-08-01 09:55 UTC, Paul-Vasylenko commented on client/src/components/pages/profile/profile-info/stats/honor-breakdown/progress-bar-block/progress-bar.scss
> +.bp3-progress-meter {
Yes, because we need a class with '-' symbol, but in Module.scss it doesn't work for me

2021-08-01 09:58 UTC, Paul-Vasylenko commented on client/src/components/pages/profile/profile-info/stats/honor-breakdown/index.tsx
> +				/>
Yes, but here "left" was like "total" value, changed it to TOTAL, now it's better

2021-08-04 10:07 UTC, kyrylo-burmelov approved these changes

2021-08-09 19:45 UTC, closed without merging