Feature/task instructions
BinaryStudioAcademy/bsa-2021-codetrainer pull request #24
Opened 2021-07-31 10:41 UTC by nikita-dnestrov

2021-07-31 20:29 UTC, kyrylo-burmelov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Task Instructions Layout](https://trello.com/c/3JvWk8ed/20-task-instructions-layout)

2021-08-04 14:40 UTC, kyrylo-burmelov requested changes

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Rank/rank.module.scss
> +}
class name can not start from number

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Rank/index.tsx
> +const Rank: React.FC<IRankProps> = (props) => {
Let's us existing Rank component. Check from develop branch /basic

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/index.tsx
> +				<Rank difficulty={6} />
You should not mock data like that. You need to mock all the data from container, component should just display the data

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/index.tsx
> +					<a>Output</a>
It should work like tabs. You should be able to navigate between tabs by clicking. Output should be empty tab for now.

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/index.tsx
> +							created by <a>Emerson Saris</a>
Same thing about mock data

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/containers/routing/index.tsx
> +		/>
You should not mock data like this. Let's create a container and mock data from container. Container should return component or several components.

```javascript
const mockData = {
   rating: 88,
   favorites: 500,
   /* .... */
}
```

See example how it should be from /users/:name route container.

You need to create route for your page too. Let it be /task/:id

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Rank/index.tsx
> +import React from 'react';
file or folder name should follow [JS quality criteria](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md#naming)

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Rank/rank.module.scss
> +:local(.rank) {
file or folder name should follow [JS quality criteria](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md#naming)

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Statistics/index.tsx
> +import React from 'react';
file or folder name should follow [JS quality criteria](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md#naming)

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Statistics/statistics.module.scss
> +:local(.info) {
file or folder name should follow [JS quality criteria](https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/source/javascript.md#naming)

2021-08-04 14:40 UTC, kyrylo-burmelov commented on client/src/components/basic/task-instructions/components/Rank/index.tsx
> +const Rank: React.FC<IRankProps> = (props) => {
components/basic/rank

2021-08-04 21:29 UTC, nikita-dnestrov commented
For some reason 'git merge develop' doesnt pull all files

2021-08-04 22:03 UTC, nikita-dnestrov commented
I've got a few questions left:

1. How to handle and debug private route? For now I placed task instructions on public route.
2. Is it ok to place task instructions in basic folder or should it be more logical to place it in common or pages or whatever you see more appropriate.

2021-08-09 07:38 UTC, kyrylo-burmelov approved these changes

2021-08-09 10:14 UTC, taras-dubyk approved these changes

2021-08-09 10:14 UTC, merged