implemented header notifications
BinaryStudioAcademy/bsa-2021-codetrainer pull request #246
Opened 2021-09-01 11:18 UTC by Paul-Vasylenko

2021-09-01 11:41 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Profile Page] connect to server NOTIFICATIONS](https://trello.com/c/u3SMjgai/167-profile-page-connect-to-server-notifications)

2021-09-01 12:36 UTC, Ev1ch requested changes

2021-09-01 12:36 UTC, Ev1ch commented on client/src/containers/header/notifications/logic/saga.ts
> +			case NotificationTypes.Common:
A lot of same objects are used. I think, you should make one initial and then use `{...initial, body: {...}}`

2021-09-02 11:42 UTC, Ev1ch approved these changes

2021-09-02 11:43 UTC, merged