add clan CRUD
BinaryStudioAcademy/bsa-2021-codetrainer pull request #26
Opened 2021-08-02 09:20 UTC by sFLASHs

2021-08-02 09:21 UTC, sFLASHs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add clan CRUD](https://trello.com/c/xZhLuRIl/23-add-clan-crud)

2021-08-03 13:50 UTC, taras-dubyk requested changes

2021-08-03 13:50 UTC, taras-dubyk commented on server/src/common/constants/services/clan/clan-is-public.ts
> +export const CLAN_IS_PUBLIC = true;
Combine all clan constants into one file.

2021-08-03 14:26 UTC, taras-dubyk approved these changes

2021-08-03 14:26 UTC, merged