Clan actions for new clan page
BinaryStudioAcademy/bsa-2021-codetrainer pull request #287
Opened 2021-09-05 17:58 UTC by Paul-Vasylenko

2021-09-05 18:28 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Clan] Add make admin](https://trello.com/c/IayvShEw/245-clan-add-make-admin)

2021-09-05 18:28 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Admin of the clan should be able to delete clan members and admins](https://trello.com/c/0HqVG074/259-admin-of-the-clan-should-be-able-to-delete-clan-members-and-admins)

2021-09-05 18:50 UTC, INTJT requested changes

2021-09-05 18:50 UTC, INTJT commented on client/src/components/pages/clans/clan/components/clan-actions/index.tsx
> +				</Button>
Delete clan button already exists in edit clan modal. Remove it from modal / clan-actions component.

2021-09-05 18:50 UTC, INTJT commented on server/src/api/profile-clan/profile-clan-api.ts
> +	});
Only admin of own clan can give to other members the admin role. Make it by middleware / service

2021-09-06 08:22 UTC, INTJT approved these changes

2021-09-06 08:24 UTC, merged