Feature/user api
BinaryStudioAcademy/bsa-2021-codetrainer pull request #29
Opened 2021-08-02 20:59 UTC by ivaschenkoo

2021-08-02 21:00 UTC, ivaschenkoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add user CRUD](https://trello.com/c/foTD17Uy/25-add-user-crud)

2021-08-03 13:35 UTC, svitlanaShymko commented on server/src/common/enum/api/users-api-path.ts
> +};
@ivaschenkoo нам також потрібно мати можливість створювати нових користувачів

2021-08-03 17:11 UTC, ivaschenkoo commented on server/src/common/enum/api/users-api-path.ts
> +};
@svitlanaShymko https://trello.com/c/foTD17Uy делал исходя из комментария "Get User and Update user will be enough for now", заодно добавил delete и get all. По поводу создания, сейчас, по идее, можно создать через auth

2021-08-03 20:14 UTC, taras-dubyk commented on server/src/common/enum/api/users-api-path.ts
> +};
@svitlanaShymko так, все правильно, якщо робити CRUD то потрібен сreate, але нам не потрібне створення юзера, в нас є реєстрація зі своїм окремим флоу.

2021-08-03 20:32 UTC, taras-dubyk requested changes

2021-08-03 20:32 UTC, taras-dubyk commented on server/src/middleware/users/users-middleware.ts
> +import { RequestHandler } from 'express';
Use dataValidationMiddleware for body validation. Check out how it is used with clan api

2021-08-13 15:41 UTC, taras-dubyk requested changes

2021-08-13 15:41 UTC, taras-dubyk commented on server/src/data/models/user/user-model.ts
> +	createdAt!: Date;
Duplicated field

2021-08-13 16:00 UTC, taras-dubyk approved these changes

2021-08-13 16:00 UTC, merged