Image uploading services
BinaryStudioAcademy/bsa-2021-codetrainer pull request #31
Opened 2021-08-03 08:51 UTC by INTJT

2021-08-03 08:52 UTC, INTJT commented
![](https://github.trello.services/images/mini-trello-icon.png) [Image uploading services](https://trello.com/c/IKQSjp4x/30-image-uploading-services)

2021-08-03 14:12 UTC, taras-dubyk requested changes

2021-08-03 14:12 UTC, taras-dubyk commented on server/src/data/repositories/images.repository.ts
> +import S3, { DeleteObjectRequest, GetObjectRequest, PutObjectRequest } from 'aws-sdk/clients/s3';
It's a service not a repository.

2021-08-04 13:39 UTC, taras-dubyk commented on server/src/api/images.controller.ts
> +				const href = await service.putImage(mapMulterFileToFile(image));
use `mapMulterFileToFile` inside `ImageService`

2021-08-05 07:50 UTC, taras-dubyk approved these changes

2021-08-05 07:50 UTC, merged