Feature/swagger
BinaryStudioAcademy/bsa-2021-codetrainer pull request #38
Opened 2021-08-05 08:29 UTC by romanortynskyi

2021-08-06 18:03 UTC, romanortynskyi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Connect SwaggerHub docs](https://trello.com/c/xrsjCBml/32-connect-swaggerhub-docs)

2021-08-08 20:37 UTC, taras-dubyk requested changes

2021-08-08 20:37 UTC, taras-dubyk commented on server/src/index.ts
> +app.use(ApiPath.API_DOCS, swaggerUI.serve, swaggerUI.setup(swaggerSpec));
move it down, after cors() etc.

2021-08-08 20:37 UTC, taras-dubyk commented on server/src/config/swagger.ts
> +		},
Add staging api too: https://staging-api.codetrain.xyz

2021-08-09 11:15 UTC, taras-dubyk approved these changes

2021-08-09 11:15 UTC, merged