Add SignUp Page with validation
BinaryStudioAcademy/bsa-2021-codetrainer pull request #4
Opened 2021-07-28 19:38 UTC by svitlanaShymko

2021-07-29 06:16 UTC, svitlanaShymko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sign-Up page Layout](https://trello.com/c/6oSK3Xhg/5-sign-up-page-layout)

2021-08-02 14:43 UTC, taras-dubyk requested changes

2021-08-02 14:43 UTC, taras-dubyk commented on client/src/assets/logo.svg
> +<svg width="553" height="81" viewBox="0 0 553 81" fill="none" xmlns="http://www.w3.org/2000/svg">
Move to assets/icons/

2021-08-02 14:43 UTC, taras-dubyk commented on client/src/components/common/cover-layout/index.tsx
> +const CoverLayout: React.FC<ICoverLayoutProps> = ({ children }) => {
Use React.FC without generic if no props

2021-08-02 15:31 UTC, taras-dubyk approved these changes

2021-08-02 15:31 UTC, merged