Patch/create task layout 2
BinaryStudioAcademy/bsa-2021-codetrainer pull request #42
Opened 2021-08-06 11:57 UTC by Paul-Vasylenko

2021-08-06 12:07 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Task Layout](https://trello.com/c/bzC3MTfa/15-create-task-layout)

2021-08-06 12:07 UTC, Paul-Vasylenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Task Layout](https://trello.com/c/bzC3MTfa/15-create-task-layout)

2021-08-08 20:25 UTC, taras-dubyk requested changes

2021-08-08 20:25 UTC, taras-dubyk commented on client/src/containers/routing/index.tsx
> +		<PublicRoute exact restricted={false} path="/task/new" component={CreateTaskPage} />
It's a private route

2021-08-09 10:15 UTC, taras-dubyk approved these changes

2021-08-09 10:15 UTC, merged