Feature/modal/clan
BinaryStudioAcademy/bsa-2021-codetrainer pull request #43
Opened 2021-08-06 12:02 UTC by nikita-dnestrov

2021-08-07 20:27 UTC, taras-dubyk requested changes

2021-08-07 20:27 UTC, taras-dubyk commented on client/src/components/modals/clan-modal/index.tsx
> +import Modal from 'react-modal';
Please use our general modal component client/src/components/modals/modal/index.tsx

2021-08-07 20:27 UTC, taras-dubyk commented on client/src/components/modals/clan-modal/components/image-upload/index.tsx
> +			<img src="https://dess.gov.ua/wp-content/uploads/2020/05/placeholder-1.png" />
Substitute external image with the local one.

2021-08-07 20:27 UTC, taras-dubyk commented on client/src/components/modals/clan-modal/index.tsx
> +	const createClan = React.useCallback((name: string) => {
Make call to server inside saga, use `http.callWebApi`

2021-08-07 20:27 UTC, taras-dubyk commented on client/src/components/modals/clan-modal/mockData.ts
> +export const token =
remove

2021-08-09 11:37 UTC, nikita-dnestrov commented
Changed maxwidth and maxheight in general modal component because it cramped content too much

2021-08-09 12:23 UTC, taras-dubyk approved these changes

2021-08-09 12:23 UTC, merged