Implemented clan modal into the home page
BinaryStudioAcademy/bsa-2021-codetrainer pull request #78
Opened 2021-08-10 12:58 UTC by nikita-dnestrov

2021-08-10 18:53 UTC, svitlua requested changes

2021-08-10 18:53 UTC, svitlua commented on client/src/components/modals/clan-modal/index.tsx
> +		if (value.length === 0) {
please use yup library for validation. As an example you can chack validation logic on SignIn and SignUp pages

2021-08-13 07:11 UTC, Ev1ch requested changes
Everything is okay except mentioned moment

2021-08-15 08:29 UTC, Paul-Vasylenko approved these changes

2021-08-15 13:35 UTC, Ev1ch approved these changes

2021-08-15 15:21 UTC, svitlua approved these changes

2021-08-15 15:22 UTC, merged