Fixed the passwords view
BinaryStudioAcademy/bsa-2021-codetrainer pull request #80
Opened 2021-08-10 16:33 UTC by AlexanderKhapchenko

I added a component to calm the QA 
I know there is an input field in the common folder
But it is a bit incomplete there
I decided to follow the example of the sign-in page and add my own modified input field 
Because if I fix it in the folder common, I think someone somewhere might break something

2021-08-10 16:36 UTC, AlexanderKhapchenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [[User setting layout] UI design does not meet mockup](https://trello.com/c/2NCWSsm1/82-user-setting-layout-ui-design-does-not-meet-mockup)

2021-08-10 17:45 UTC, svitlua requested changes
Please, dont make unnecessary copies of common components. You can refactor according the QA requirement and use FormInput component from src/components/common/form-input/
If we make copies of components it will be very hard to maitain the project in the future.
We also need to refactor usage of input field in SignIn Page to unify the look and functionality of form input. SignIn Page was created during the first days, and at that moment we didn't have opportunity to use common components. Lets refactor and not make thins more complicated.

2021-08-10 18:20 UTC, Paul-Vasylenko commented
Agree with @svitlua , it would be great if we use the same component here. You can use unnecessary fields (e.g. {name?: string}), so that shouldn't crash anything ion other places. If the problem was with onClick for 'eye' you shoud just add that function to container and ,by props, send it to every component.

**As for other changes - looks great!**

2021-08-11 09:40 UTC, Paul-Vasylenko approved these changes

2021-08-11 09:46 UTC, svitlua commented on client/src/components/pages/setting/components/information/index.tsx
> +	name: Yup.string().min(2, 'Too short').max(50, 'Too long').required('Required'),
Please, use here QA requirements for validation:
https://trello.com/c/xusLg7a2/44-sign-in-sign-up-notifications

or simply copy from here:
https://github.com/BinaryStudioAcademy/bsa-2021-codetrainer/blob/patch/username/client/src/components/pages/sign-up/index.tsx

2021-08-11 10:01 UTC, svitlua approved these changes

2021-08-11 10:05 UTC, merged