Patch/blueprint removal
BinaryStudioAcademy/bsa-2021-codetrainer pull request #96
Opened 2021-08-12 15:42 UTC by nikita-dnestrov

Got rid of most blueprint, except in CreateTaskSettings because I dont understand how to replace blueprint radio buttons with images without remaking the whole component.

2021-08-13 20:00 UTC, nikita-dnestrov commented
There was a weird es-lint conflict with /server/src/types/user/user-fields.ts which referenced unexisting files so I had to modify it despite having nothing to do with it.

2021-08-13 20:51 UTC, Paul-Vasylenko requested changes

2021-08-13 20:51 UTC, Paul-Vasylenko commented on client/src/components/basic/info-popover/index.tsx
> +};
need to discuss which version to have
https://github.com/BinaryStudioAcademy/bsa-2021-codetrainer/pull/101

2021-08-13 20:51 UTC, Paul-Vasylenko commented on client/src/components/basic/info-popover/info-popover.module.scss
> +	color: #282828;
change to variable

2021-08-14 08:21 UTC, Paul-Vasylenko approved these changes

2021-08-14 08:21 UTC, merged